### ISSUE TITLE
Add note to README that only JS is supported

### ISSUE THREAD

**Issue by chrisbodhi** [lithin/serverless-run-function-plugin#10]
I wouldn't be mad if you added support for other runtimes, though. 😸

**Comment by lithin** [comment]
Hey @chrisbodhi I believe this functionality is now supported in serverless framework by default if you run `sls invoke local` :)

https://serverless.com/framework/docs/providers/aws/cli-reference/invoke-local/

**Comment by chrisbodhi** [comment]
Delightful! Thanks for letting me know.
