### ISSUE TITLE
Consistent 'function' CLI paramater

### ISSUE THREAD

**Issue by dsole** [lithin/serverless-run-function-plugin#3]
Thanks for the plugin.
Can I suggest that the "functionName" CLI parameter be renamed to "function" so that it is consistent with the built-in ["invoke" command](https://github.com/serverless/serverless/blob/master/docs/03-cli-reference/03-invoke.md) ?

That way I can interchange between 
`serverless invoke --function hello`
and
`serverless run --function hello`

**Comment by lithin** [comment]
We've actually had a whole discussion about this in our company :) What serverless refers to as a "function" keeps changing all the time - sometimes it's an artefact of it, sometimes it's an object with some info about the function, sometimes it's the name...

I agree that they should be the same but I feel `functionName` is more precise. I'm happy to be proven wrong though ;)
