### ISSUE TITLE
The function name is being used as the handler name.

### ISSUE THREAD

**Issue by dsole** [lithin/serverless-run-function-plugin#4]
In the code the function name is being used to locate the handler function.
So if the exported function's name doesn't match the function name in serverless.yml, it throws an error.

Here's an example with the configured name is 'hello' and the handler function is 'helloHandler':

_serverless.yml_

``` yml
functions:
  hello:
    handler: index.helloHandler
```

_index.js_

``` javascript
'use strict';
module.exports.helloHandler = (event, context, cb) => {
  cb(null, { message: 'Go Serverless v1.0! Your function executed successfully!', event });
};
```

Then the command
`serverless run -f hello`

produces the message

```
  Type Error ---------------------------------------------
     importedHandler[functionName] is not a function
```

This is because the "functionName" is being used  rather than the handler's name.

_run.js_

``` javascript
  const functionObj = serverless.service.getFunction(functionName);
...
  importedHandler[functionName](
    event,
    contextFn(functionName, serverless),
    callbackFn(serverless)
  );
```

**Comment by lithin** [comment]
Fixed by @dsole - thank you!!
