### ISSUE TITLE
Publish new version to NPM

### ISSUE THREAD

**Issue by Titozzz** [lithin/serverless-run-function-plugin#6]
Actual version is still broken with functionName.

**Comment by lithin** [comment]
Hey sorry not sure what you mean with the functionName?

**Comment by DianaIonita** [comment]
Titozzz is likely referring to this commit https://github.com/lithin/serverless-run-function-plugin/commit/21487c5ca0eb31f90e8e686ba1f74da431bd35c4
Please push this to npm, I've had to manually tweak my node_modules

**Comment by lithin** [comment]
Done @DianaIonita @Titozzz - let me know if it works for you now
